Repository gyesswhat/groupproject3, pull requests merged in 2024-02, with the labels that each got.

#9 refactor: 폴더 구조 리팩토링
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/FoodType.js
  frontend/src/Logo.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/index.js
  frontend/src/pages/login/Login.js
  frontend/src/pages/login/index.js
  frontend/src/pages/main/FoodType.js
  frontend/src/pages/main/Logo.js
  frontend/src/pages/main/Main.js
  frontend/src/pages/main/PlaceDropdown.js
  frontend/src/pages/main/Posts.js
  frontend/src/pages/main/index.js
  frontend/src/pages/main/main.const.js
  frontend/src/setProxy.js
  frontend/src/test.js
Labels: FE

#14 feat : add postdetail
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Fakeuser.js
  frontend/src/pages/detail/CommentForm.js
  frontend/src/pages/detail/PostDetail.js
  frontend/src/pages/detail/Status.js
  frontend/src/pages/detail/detail.const.js
  frontend/src/pages/detail/index.js
  frontend/src/pages/index.js
  frontend/src/pages/login/Login.js
  frontend/src/pages/login/Register.js
  frontend/src/pages/login/bank.const.js
  frontend/src/pages/login/index.js
  frontend/src/pages/main/FoodType.js
  frontend/src/pages/main/Main.js
  frontend/src/pages/main/PlaceDropdown.js
  frontend/src/pages/main/Posts.js
  frontend/src/pages/main/Topbar.js
  frontend/src/pages/main/index.js
  frontend/src/pages/main/main.const.js
  frontend/src/pages/main/main.style.js
  frontend/src/pages/main/posts.const.js
Labels: feature, FE

#15 refactor: 멘토링 피드백 및 리팩토링
  frontend/.eslintrc.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/auth/Login.jsx
  frontend/src/components/auth/Register.jsx
  frontend/src/components/auth/auth.const.js
  frontend/src/components/auth/index.js
  frontend/src/components/detail/CommentForm.jsx
  frontend/src/components/detail/PostContents.jsx
  frontend/src/components/detail/PostDetail.jsx
  frontend/src/components/detail/StatusList.jsx
  frontend/src/components/detail/detail.const.js
  frontend/src/components/detail/index.js
  frontend/src/components/header/Header.jsx
  frontend/src/components/header/Logo.jsx
  frontend/src/components/header/index.js
  frontend/src/components/index.js
  frontend/src/components/main/Main.jsx
  frontend/src/components/main/index.js
  frontend/src/components/main/main.const.js
  frontend/src/components/main/main.style.js
  frontend/src/components/menu/FoodTypeItem.jsx
  frontend/src/components/menu/Menu.jsx
  frontend/src/components/menu/PlaceDropdown.jsx
  frontend/src/components/menu/index.js
  frontend/src/components/menu/menu.const.js
  frontend/src/components/menu/menu.style.js
  frontend/src/components/posts/DeliveryItem.jsx
  frontend/src/components/posts/Posts.jsx
  frontend/src/components/posts/index.js
  frontend/src/components/posts/posts.const.js
  frontend/src/pages/detail/index.js
  frontend/src/pages/index.js
  frontend/src/pages/login/index.js
  frontend/src/pages/main/Main.js
  frontend/src/pages/main/Posts.js
  frontend/src/pages/main/index.js
Labels: FE

#11 feat: comment 관련 기능 추가
  backend/src/main/java/com/example/delivery/controller/CommentController.java
  backend/src/main/java/com/example/delivery/dto/CommentDto.java
  backend/src/main/java/com/example/delivery/dto/CommentListDto.java
  backend/src/main/java/com/example/delivery/entity/Comment.java
  backend/src/main/java/com/example/delivery/repository/CommentRepository.java
  backend/src/main/java/com/example/delivery/service/CommentService.java
Labels: feature, BE

#16 refactor: postRepository / participantRepository 쿼리 네이티브쿼리로 수정 + 수정 영향으로 Dto 일부 수정
  backend/src/main/java/com/example/delivery/dto/ParticipantListDto.java
  backend/src/main/java/com/example/delivery/dto/PostDetailDto.java
  backend/src/main/java/com/example/delivery/dto/PostListDto.java
  backend/src/main/java/com/example/delivery/entity/Participant.java
  backend/src/main/java/com/example/delivery/entity/Post.java
  backend/src/main/java/com/example/delivery/repository/ParticipantRepository.java
  backend/src/main/java/com/example/delivery/repository/PostRepository.java
Labels: BE

#17 refactor: ParticipantRepository, CommentRepository 네이티브 쿼리 수정, Participant 복합키 반영
  backend/src/main/java/com/example/delivery/entity/Comment.java
  backend/src/main/java/com/example/delivery/entity/Participant.java
  backend/src/main/java/com/example/delivery/entity/ParticipantPK.java
  backend/src/main/java/com/example/delivery/repository/CommentRepository.java
  backend/src/main/java/com/example/delivery/repository/ParticipantRepository.java
  backend/src/main/java/com/example/delivery/service/PostService.java
Labels: BE

#19 feat: 마이페이지 주문 히스토리 기능 구현
  backend/src/main/java/com/example/delivery/controller/UserController.java
  backend/src/main/java/com/example/delivery/dto/PostDto.java
  backend/src/main/java/com/example/delivery/entity/Comment.java
  backend/src/main/java/com/example/delivery/entity/ParticipantPK.java
  backend/src/main/java/com/example/delivery/entity/Post.java
  backend/src/main/java/com/example/delivery/repository/PostRepository.java
  backend/src/main/java/com/example/delivery/service/PostService.java
  backend/src/main/java/com/example/delivery/service/UserService.java
Labels: BE

#22 fix: api 명세서에 맞게 코드 수정
  backend/src/main/java/com/example/delivery/controller/CommentController.java
  backend/src/main/java/com/example/delivery/dto/CancelHostDto.java
  backend/src/main/java/com/example/delivery/dto/CancelPartDto.java
  backend/src/main/java/com/example/delivery/dto/CommentDto.java
  backend/src/main/java/com/example/delivery/dto/CommentListDto.java
  backend/src/main/java/com/example/delivery/dto/LoginDto.java
  backend/src/main/java/com/example/delivery/dto/ParticipantDto.java
  backend/src/main/java/com/example/delivery/dto/ParticipantListDto.java
  backend/src/main/java/com/example/delivery/dto/PostDetailDto.java
  backend/src/main/java/com/example/delivery/dto/PostDto.java
  backend/src/main/java/com/example/delivery/dto/PostListDto.java
  backend/src/main/java/com/example/delivery/dto/UserDetailDto.java
  backend/src/main/java/com/example/delivery/dto/UserDto.java
  backend/src/main/java/com/example/delivery/dto/UserEditDto.java
  backend/src/main/java/com/example/delivery/entity/Comment.java
  backend/src/main/java/com/example/delivery/service/CommentService.java
Labels: BE

#24 fix: 주문 히스토리 조회, 스케줄러 관련 오류 수정
  backend/src/main/java/com/example/delivery/PostStatusScheduler.java
  backend/src/main/java/com/example/delivery/entity/Post.java
Labels: BE

#23 feat: add server connecting code
  frontend/public/assets/nav-icon1.svg
  frontend/public/assets/nav-icon2.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Fakeuser.js
  frontend/src/components/auth/BankOptions.jsx
  frontend/src/components/auth/Login.jsx
  frontend/src/components/auth/Register.jsx
  frontend/src/components/auth/index.js
  frontend/src/components/detail/CommentForm.jsx
  frontend/src/components/detail/OrderFailed.jsx
  frontend/src/components/detail/PostContents.jsx
  frontend/src/components/detail/PostDetail.jsx
  frontend/src/components/detail/index.js
  frontend/src/components/header/Header.jsx
  frontend/src/components/index.js
  frontend/src/components/main/main.style.js
  frontend/src/components/mypage/MyPage.jsx
  frontend/src/components/mypage/Navigator.jsx
  frontend/src/components/mypage/OrdersPage.jsx
  frontend/src/components/mypage/ProfilePage.jsx
  frontend/src/components/mypage/index.js
  frontend/src/components/posts/DeliveryItem.jsx
  frontend/src/components/posts/Posts.jsx
  frontend/src/components/posts/WritePost.jsx
  frontend/src/components/posts/posts.const.js
Labels: help wanted, feature, FE
